# **********************
# *** fia-svc VALUES ***
# **********************

# Specify the twelve-digit AWS account ID where the service is being deployed.
awsAccountID:

# Specify the AWS region.
awsRegion: us-east-1

# Customer/tenant associated with the deployment (required).
customer:

# Application tier associated with the deployment (required).
tier:

# Specify the name of the service being deployed.
name:

# Specify a list of imagePullSecrets
imagePullSecrets: []

# Name of EKS/ROSA cluster.
clusterName:

# Top-level domains for DNS
dnsZone: apps.example.com

additionalAnnotations: {}


# ********************************************
# *** WORKLOAD, CONFIGURATION, and VOLUMES ***
# ********************************************

# Deploy workload using traditional K8s Deployment resource.
deployment:
  enabled: true

# Specify filename, path, and contents of JSON-based or INI configurations.
# For JSON-based configurations, configFilename determines the name of the configuration file.
# For INI configurations (Spring Boot applications), configFilename must contain `.properties` and
# filenames are defined in the configuration itself.
#
# JSON-based configuration example:
# config:
#   foo: baaz
#   quux:
#     key: value
#
# INI configuration example:
# configFilename: system.properties
# config:
#   application.properties: |
#     key=value
#     another.key="some other value"
#   database.properties: |
#     database.host=something
#     database.port=5432
configFilename: config.json
configPath: /data/config
config: {}

# Specify the image repository and tag for the service.
image:
  repository: ghcr.io/org/placeholder
  pullPolicy: IfNotPresent
  tag: latest

# Specify a list of additional name/value environment variables.
env: []
# - name: FOO
#   value: "BAR"
# - name: MY_SECRET
#   valueFrom:
#     secretKeyRef:
#       name: my-k8s-secret
#       key: secret-key

# Enable deployment of a Kubernetes Job/CronJob with a separate image, in addition to Rollout or Deployment.
# Providing a value for job.cronSchedule will enable CronJob.
job:
  enabled: false
  command: []
  args: []
  concurrencyPolicy: Forbid
# cronSchedule: '* * * * *'
  image:
    repository: ghcr.io/org/placeholder
    pullPolicy: IfNotPresent
    tag: latest
  # Jobs are cleaned after 10 days.
  ttlSecondsAfterFinished: 864000

initialProbeDelay: 10
livenessProbePath: /ping
readinessProbePath: /ping

# Specify additional pod annotations.
# Pod annotations are used to configure IAM role assumption on kOps clusters.
podAnnotations: {}

# Specify a list of Persistent Volume Claims (PVCs) to be created.
persistentVolumeClaims:
# - name: my-pvc
#   labels: {}
#   annotations: {}
#   accessModes: ["ReadWriteMany"]      # Defaults to ["ReadWriteOnce"]
#   mountEnabled: false                 # Boolean to mount the PVC into the pod. Defaults to true.
#   mountPath: /data/storage            # Mount path inside the pod.
#   readOnly: false                     # Boolean to mount the PVC as read-only. Defaults to false.
#   size: 10Gi                          # Defaults to "1Gi"
#   storageClassName: standard
#   volumeMode: Filesystem
#   selector:
#       matchLabels: { app: my-app }

# Specify additional volumes to be mounted.
# ConfigMap volume is mounted automatically if config is defined.
# Any PVCs defined above are automatically mounted if mountEnabled is true.
volumes:


# ************
# *** RBAC ***
# ************

serviceAccount:
  create: false
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated.
  # name: default
role:
  rules:
  # - apiGroups: ["apps"]
  #   resources: ["deployments"]
  #   verbs: ["get", "patch", "update"]
  # - apiGroups: ["argoproj.io"]
  #   resources: ["rollouts"]
  #   verbs: ["get", "patch", "update"]


# ***************
# *** SECRETS ***
# ***************

secretProviderClasses:
# - name: example-aws-secrets
#   provider: aws
#   metadata:
#     annotations: {}
#     labels: {}
#   spec:
#     parameters:
#       objects: |
#         - objectName: "/my/secret/path"
#           objectType: "secretsmanager"
#           objectVersion: ""
# - name: example-vault-secrets
#   provider: vault
#   metadata:
#     annotations: {}
#     labels: {}
#   spec:
#     parameters:
#       vaultAddress: "https://vault.example.com"
#       roleName: "k8s-role"
#     secretObjects:
#       - secretName: my-vault-secret
#         type: Opaque
#         data:
#           - objectName: "secret/data/app"
#             key: token


# *******************************
# ***** SERVICE and INGRESS *****
# *******************************

service:
  type: ClusterIP
  containerPort: 8080
  port: 80

# Private ingress
# Ingress is required when using Argo CD rollouts.
ingress:
  enabled: true
  className: openshift-default
  annotations:
    route.openshift.io/termination: edge
  hosts:
  - host: someapp
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local


# *********************************
# ***** RESOURCES and SCALING *****
# *********************************

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
replicaCount: 1
resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
revisionHistoryLimit: 2


# **************************************
# ***** POD PLACEMENT and SECURITY *****
# **************************************

affinity: {}
nodeSelector: {}
tolerations: []

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
